# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Next.js CI staging

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: [self-hosted, Linux, X64, staging]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: mv .env.staging .env
    - run: npm run build
    - run: pm2 delete ecom-staging-front 2> /dev/null || true 
    - run: pm2 start 'npx next start -p 4001' --name ecom-staging-front
